##### Εισαγωγή notebook καθαρισμού δεδομένων από πίνακα products
- Σε αυτό το notebook θα επικεντρωθούμε στην ανάλυση των δεδομένων του 1ου datframe, "products" το οποίο περιέχει πληροφορίες για την εκάστοτε υπηρεσία. Ύστετα θα ενώσουμε τους 2 πίνακες για να έχουμε το τελικό Dataset. Εισάγουμε τα δεδομένα από το προηγούμενο notebook όπου και τα είχαμε κατεβάσει για αποφυγή πολυπλοκότητας και προχωράμε στην επεξεργασία. Η εισαγωγή γίνεται διαβάζοντας το parquet αρχείο που αποθηκεύσαμε στο προηγούμενο notebook, και μετατρέποντας το σε datframe μέσω της αντίστοιχης pandas εντολής
- Το περίεργο - δύσκολο κομμμάτι της ανάλυσης αυτής, είνα ότι ενώ ο πίνακας με τα δεδομένα product είναι πλήρως ανοιγμένος, το πλήθος των στηλών του είναι μεταβαλόμενο ανά υπηρεσία. Οπότε θα πρέπει να ακολουθηθεί κάποια τεχνική, προκειμένου ο κώδικας να γίνει γενικός και να τρέχει για όλες τις υπηρεσίες. (Ενδεικτικά στο ec2 ο products έχει 79 στήλες ίσως και παραπάνω, ενώ στο s3 έχει 25, και ανάλογα στους άλλους παρόχους)

In [2]:
import pandas as pd

df_terms_final = pd.read_parquet('cleaned_aws_terms.parquet')
df_products = pd.read_parquet('cleaned_aws_products.parquet')

print("Terms shape:", df_terms_final.shape)
print("Products shape:", df_products.shape)

df_terms_final.head()

Terms shape: (61473, 5)
Products shape: (100000, 79)

,sku,rateCode,description,unit,priceUSD
0,354NCHJF54DDH7TQ,354NCHJF54DDH7TQ.JRTCKXETXF.6YS6EN2CT7,$21.254 per On Demand RHEL with SQL Server Ent...,Hrs,21.254
1,UM7U8QBMJUK7JDGA,UM7U8QBMJUK7JDGA.JRTCKXETXF.6YS6EN2CT7,$12.744 per On Demand Linux with SQL Std c5.18...,Hrs,12.744
2,NH7HRNPDBQYMGPWJ,NH7HRNPDBQYMGPWJ.JRTCKXETXF.6YS6EN2CT7,$4.204 per On Demand SUSE c5.18xlarge Instance...,Hrs,4.204
3,4MTNQ5R6GPSE3D5C,4MTNQ5R6GPSE3D5C.JRTCKXETXF.6YS6EN2CT7,$18.029 per On Demand RHEL with SQL Standard c...,Hrs,18.029
4,JMMKH6VED2E7GWQQ,JMMKH6VED2E7GWQQ.JRTCKXETXF.6YS6EN2CT7,$5.472 per On Demand Windows with SQL Web with...,Hrs,5.472

In [3]:
df_products.head()

,sku,productFamily,attributes.servicecode,attributes.location,attributes.locationType,attributes.instanceType,attributes.currentGeneration,attributes.instanceFamily,attributes.vcpu,attributes.physicalProcessor,...,attributes.volumeType,attributes.maxVolumeSize,attributes.maxIopsvolume,attributes.maxIopsBurstPerformance,attributes.maxThroughputvolume,attributes.instance,attributes.snapshotarchivefeetype,attributes.ebsOptimized,attributes.elasticGraphicsType,attributes.instanceCapacity-10xlarge
0,RSH2Y67N4H4CFBQ4,Compute Instance,AmazonEC2,Asia Pacific (Malaysia),AWS Region,c7gd.medium,Yes,Compute optimized,1,AWS Graviton3 Processor,...,None,None,None,None,None,None,None,None,None,None
1,YHBHTMRVRUX8M33Y,Compute Instance,AmazonEC2,Asia Pacific (Malaysia),AWS Region,m7i.large,Yes,General purpose,2,Intel Xeon Scalable (Sapphire Rapids),...,None,None,None,None,None,None,None,None,None,None
2,JSEGQBVEG2Y4NYJR,Compute Instance,AmazonEC2,Asia Pacific (Thailand),AWS Region,c6in.24xlarge,Yes,Compute optimized,96,Intel Xeon 8375C (Ice Lake),...,None,None,None,None,None,None,None,None,None,None
3,646B9QM23GWYVTAK,Compute Instance,AmazonEC2,Africa (Cape Town),AWS Region,c7i.xlarge,Yes,Compute optimized,4,Intel Xeon Scalable (Sapphire Rapids),...,None,None,None,None,None,None,None,None,None,None
4,SSMSW7PJQYNKBTE4,Compute Instance,AmazonEC2,AWS GovCloud (US-West),AWS Region,m6i.large,Yes,General purpose,2,Intel Xeon 8375C (Ice Lake),...,None,None,None,None,None,None,None,None,None,None